### ISSUE TITLE
Freezes when app navigates to another page

### ISSUE THREAD

**Issue by Vingtoft** [StonePack/widget_marquee#1]
First of all: Thank you for developing this awesome library! As far as I can tell, this plugin is the only marquee that supports widgets and continuously loop. 

I do have one problem: After implementing nested navigation, whenever the app navigates away from the page that uses this plugin, the app freezes and crashes. 

The reason for this is unkonwn to me, but I can point out exactly where it happens: 

In the `while` loop within the `scroll` function.

Example: If I edit your code and inserts a print-statement in the `while` loop, the console prints out ten of thousands of "Hangs".
```

while (scrollController.hasClients) {
   print('Hangs');
}

```

Do you have any idea how this problem can be solved? 

Cheers

**Comment by fingersonfire** [comment]
Hey @Vingtoft ,

Sorry for the super late response, I didn't even notice that this issue had been opened. Are you utilizing the version that is currently up on pub.dev and is this still occurring?

**Comment by RelicOfTesla** [comment]
pub.dev version is too old.

**Comment by fingersonfire** [comment]
I'm gonna mark this as resolved! The latest version has been published to [pub.dev](https://pub.dev/packages/widget_marquee) as of today.
